version: "3"
services:
  mariadb:
    build:
      context: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    env_file:
      - .env
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 1s
      timeout: 5s
      retries: 10
    mem_limit: '512m'
    volumes:
      - "./volume/mysql/data:${MARIADB_DATA_DIR}"
      - "./volume/mysql/logs:${MARIADB_LOG_DIR}"

  svws:
    build: svws
    depends_on:
      mariadb:
        condition: service_healthy
    links:
      - mariadb
    env_file:
      - .env
    ports:
      - "8443:8443"
    mem_limit: '1g'
    volumes:
      - ./volume/keystore:/etc/app/svws/keystore